<?php

namespace App\Core;

class Base
{
    protected $autoBlame = true;
    protected $hasGuid = true;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (BaseModel $baseModel) {
            if ($baseModel->hasGuid && empty($baseModel->guid)) {
                $baseModel->setAttribute('guid', GuidHelper::getGuid());
            }
            if ($baseModel->autoBlame) {
                if (empty($baseModel->created_by) || empty($baseModel->updated_by)) {
                    $baseModel->setAttribute('created_by', Auth::user()->id);
                    $baseModel->setAttribute('updated_by', Auth::user()->id);
                }
            }
        });
    }
}